[git]
conventional_commits = true
filter_unconventional = false
require_conventional = false
commit_parsers = [
    { message = "^chore\\(release\\):", skip = true },
    { message = ".*", group = "Changes"},
]
sort_commits = "newest"
